-- settlement-server: Settlement domain tables
-- Consolidated from api-server migrations: V0.0.6, V0.0.12, V0.0.13, V0.6.1

CREATE TABLE settlement_item (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           BIGINT         NOT NULL,
    order_item_id      BIGINT         NOT NULL,
    seller_id          BIGINT         NOT NULL,
    target_id          BIGINT         NOT NULL,
    target_type        VARCHAR(50)    NOT NULL,
    payment_id         BIGINT         NOT NULL,
    type               VARCHAR(50)    NOT NULL,
    status             VARCHAR(50),
    paid_amount        NUMERIC(38, 2),
    pg_fee             NUMERIC(38, 2),
    platform_fee       NUMERIC(38, 2),
    settlement_amount  NUMERIC(38, 2),
    retry_count        INTEGER        NOT NULL DEFAULT 0,
    expected_date      DATE,
    confirmed_at       TIMESTAMP(6)   NOT NULL,
    cancelled_at       TIMESTAMP(6),
    settled_at         TIMESTAMP(6),
    history_id         BIGINT,
    origin_id          BIGINT,
    created_at         TIMESTAMP(6)   NOT NULL,
    updated_at         TIMESTAMP(6)   NOT NULL,
    created_by         VARCHAR(255),
    updated_by         VARCHAR(255),

    CONSTRAINT uk_order_item_id_type UNIQUE (order_item_id, type),
    CONSTRAINT uk_order_id_order_item_id_type UNIQUE (order_id, order_item_id, type)
);

CREATE INDEX idx_settlement_status_created_retry ON settlement_item (status, created_at, retry_count);
CREATE INDEX idx_settlement_order_id ON settlement_item (order_id);
CREATE INDEX idx_settlement_item_payment_id ON settlement_item (payment_id);
CREATE INDEX idx_settlement_item_order_item_id ON settlement_item (order_item_id);
CREATE INDEX idx_settlement_item_seller_id ON settlement_item (seller_id);

CREATE TABLE settlement_queue (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_item_id  BIGINT       NOT NULL UNIQUE,
    status              VARCHAR(50)  NOT NULL,
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6),

    CONSTRAINT fk_settlement_queue_item
        FOREIGN KEY (settlement_item_id) REFERENCES settlement_item (id)
);

CREATE TABLE settlement_history (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id             BIGINT         NOT NULL,
    settlement_date       DATE           NOT NULL,
    item_count            INTEGER        NOT NULL,
    sales_amount          NUMERIC(38, 2),
    pg_fee                NUMERIC(38, 2),
    platform_fee          NUMERIC(38, 2),
    settlement_amount     NUMERIC(38, 2),
    settled_at            TIMESTAMP(6),
    status                VARCHAR(50),
    reference_history_id  BIGINT,

    CONSTRAINT uk_seller_settlement_date UNIQUE (seller_id, settlement_date)
);
